In [17]:
from random import random
import operator
from functools import reduce
from collections import namedtuple
from queue import PriorityQueue, SimpleQueue, LifoQueue

import numpy as np

In [18]:
PROBLEM_SIZE = 5
NUM_SETS = 10
SETS = tuple(
    np.array([random() < 0.3 for _ in range(PROBLEM_SIZE)]) for _ in range(NUM_SETS)
)
State = namedtuple("State", ["taken", "not_taken"])

In [19]:
def goal_check(state):
    return np.all(
        reduce(
            np.logical_or,
            [SETS[i] for i in state.taken],
            np.array([False for _ in range(PROBLEM_SIZE)]),
        )
    )

#Distanza dalla copertura completa del nuovo stato. Più basso = più coperto
def distance(state):
    return PROBLEM_SIZE - sum(
        reduce(
            np.logical_or,
            [SETS[i] for i in state.taken],
            np.array([False for _ in range(PROBLEM_SIZE)]),
        )
    )

In [20]:
assert goal_check(State(set(range(NUM_SETS)), set())), "Problem not solvable"

SimpleQueue = FIFO -> **Breadth** first

LifoQueue -> **Depth** first
 - Molto veloce
 - Soluzione sub-optimale, possibilmente contiene più elementi di quelli necessari per la soluzione minima (***es*** 5 step 5 tiles/sets rispetto a 26 steps e 2 tiles/sets del breadth)

In [30]:
frontier = PriorityQueue()
state = State(set(), set(range(NUM_SETS)))
frontier.put((distance(state), state))

counter = 0
_, current_state = frontier.get()
while not goal_check(current_state):
    counter += 1
    for action in current_state.not_taken:
        new_state = State(
            current_state.taken ^ {action}, current_state.not_taken ^ {action}
        )
        frontier.put((distance(new_state), new_state))
    _, current_state = frontier.get()

print(f"Solved in {counter:,} steps ({len(current_state.taken)} tiles)")

Solved in 3 steps (3 tiles)


In [32]:
current_state

State(taken={0, 9, 1}, not_taken={2, 3, 4, 5, 6, 7, 8})

In [23]:
SETS

(array([ True,  True, False, False,  True]),
 array([False, False, False,  True,  True]),
 array([False, False, False, False, False]),
 array([False,  True, False, False, False]),
 array([False,  True, False, False, False]),
 array([False, False, False,  True, False]),
 array([False,  True, False, False, False]),
 array([False, False, False, False, False]),
 array([False, False, False, False, False]),
 array([False, False,  True, False, False]))

In [24]:
goal_check(current_state)

True

In some cases the greedy approcach doesn't return the best possible solution because it started moving in one direction but was not the best one to continue with

# Examples
Without greedy we obtain the best solution

![Image of the result without greedy](Images\Best_in_greedy_without.png "With greedy")

With greedy we obtain the best solution with the starting point taken

![Image of the result with greedy approach](Images\Best_in_greedy_with.png "With greedy")
